<?php
/**
 * ContactsCustomFieldType
 *
 * PHP version 8.1
 *
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-equisoft1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Equisoft\SDK\EquisoftConnect\Model;

/**
 * ContactsCustomFieldType Class Doc Comment
 *
 * @description Custom field type.
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum ContactsCustomFieldType: string
{
    case TEXT_FIELD = 'text_field';

    case NUMERIC_FIELD = 'numeric_field';

    case VD_FIELD = 'vd_field';

    case BOOLEAN_FIELD = 'boolean_field';

    case DATE_FIELD = 'date_field';

    case MONEY_FIELD = 'money_field';

    case UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';
}


