<?php
/**
 * ContactsCreateAdditionalInformationPayload
 *
 * PHP version 8.1
 *
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-equisoft1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Equisoft\SDK\EquisoftConnect\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Equisoft\SDK\EquisoftConnect\ObjectSerializer;

/**
 * ContactsCreateAdditionalInformationPayload Class Doc Comment
 *
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ContactsCreateAdditionalInformationPayload implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'contacts.CreateAdditionalInformationPayload';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'isDeceased' => 'bool',
        'deceasedDate' => '\DateTime',
        'isSmoker' => 'bool',
        'smokerEndDate' => '\DateTime',
        'birthDate' => '\DateTime',
        'language' => 'int',
        'organizationDateCreated' => '\DateTime',
        'organizationDateClosed' => '\DateTime',
        'numberOfEmployees' => 'int',
        'companyValue' => 'int',
        'annualGrowth' => 'int',
        'companyStage' => 'int',
        'revenue' => '\Equisoft\SDK\EquisoftConnect\Model\ContactsCreateRevenuePayload',
        'netProfits' => 'int',
        'incorporationLocation' => 'int',
        'payroll' => 'int',
        'endOfFinancialYear' => 'string',
        'registrationNumbers' => '\Equisoft\SDK\EquisoftConnect\Model\ContactsCreateRegistrationNumbersPayload',
        'knownSince' => '\DateTime',
        'endDate' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'isDeceased' => null,
        'deceasedDate' => 'date',
        'isSmoker' => null,
        'smokerEndDate' => 'date',
        'birthDate' => 'date',
        'language' => null,
        'organizationDateCreated' => 'date',
        'organizationDateClosed' => 'date',
        'numberOfEmployees' => null,
        'companyValue' => null,
        'annualGrowth' => null,
        'companyStage' => null,
        'revenue' => null,
        'netProfits' => null,
        'incorporationLocation' => null,
        'payroll' => null,
        'endOfFinancialYear' => null,
        'registrationNumbers' => null,
        'knownSince' => 'date',
        'endDate' => 'date'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'isDeceased' => false,
        'deceasedDate' => true,
        'isSmoker' => false,
        'smokerEndDate' => true,
        'birthDate' => true,
        'language' => true,
        'organizationDateCreated' => true,
        'organizationDateClosed' => true,
        'numberOfEmployees' => true,
        'companyValue' => true,
        'annualGrowth' => true,
        'companyStage' => true,
        'revenue' => true,
        'netProfits' => true,
        'incorporationLocation' => true,
        'payroll' => true,
        'endOfFinancialYear' => true,
        'registrationNumbers' => true,
        'knownSince' => true,
        'endDate' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'isDeceased' => 'isDeceased',
        'deceasedDate' => 'deceasedDate',
        'isSmoker' => 'isSmoker',
        'smokerEndDate' => 'smokerEndDate',
        'birthDate' => 'birthDate',
        'language' => 'language',
        'organizationDateCreated' => 'organizationDateCreated',
        'organizationDateClosed' => 'organizationDateClosed',
        'numberOfEmployees' => 'numberOfEmployees',
        'companyValue' => 'companyValue',
        'annualGrowth' => 'annualGrowth',
        'companyStage' => 'companyStage',
        'revenue' => 'revenue',
        'netProfits' => 'netProfits',
        'incorporationLocation' => 'incorporationLocation',
        'payroll' => 'payroll',
        'endOfFinancialYear' => 'endOfFinancialYear',
        'registrationNumbers' => 'registrationNumbers',
        'knownSince' => 'knownSince',
        'endDate' => 'endDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'isDeceased' => 'setIsDeceased',
        'deceasedDate' => 'setDeceasedDate',
        'isSmoker' => 'setIsSmoker',
        'smokerEndDate' => 'setSmokerEndDate',
        'birthDate' => 'setBirthDate',
        'language' => 'setLanguage',
        'organizationDateCreated' => 'setOrganizationDateCreated',
        'organizationDateClosed' => 'setOrganizationDateClosed',
        'numberOfEmployees' => 'setNumberOfEmployees',
        'companyValue' => 'setCompanyValue',
        'annualGrowth' => 'setAnnualGrowth',
        'companyStage' => 'setCompanyStage',
        'revenue' => 'setRevenue',
        'netProfits' => 'setNetProfits',
        'incorporationLocation' => 'setIncorporationLocation',
        'payroll' => 'setPayroll',
        'endOfFinancialYear' => 'setEndOfFinancialYear',
        'registrationNumbers' => 'setRegistrationNumbers',
        'knownSince' => 'setKnownSince',
        'endDate' => 'setEndDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'isDeceased' => 'getIsDeceased',
        'deceasedDate' => 'getDeceasedDate',
        'isSmoker' => 'getIsSmoker',
        'smokerEndDate' => 'getSmokerEndDate',
        'birthDate' => 'getBirthDate',
        'language' => 'getLanguage',
        'organizationDateCreated' => 'getOrganizationDateCreated',
        'organizationDateClosed' => 'getOrganizationDateClosed',
        'numberOfEmployees' => 'getNumberOfEmployees',
        'companyValue' => 'getCompanyValue',
        'annualGrowth' => 'getAnnualGrowth',
        'companyStage' => 'getCompanyStage',
        'revenue' => 'getRevenue',
        'netProfits' => 'getNetProfits',
        'incorporationLocation' => 'getIncorporationLocation',
        'payroll' => 'getPayroll',
        'endOfFinancialYear' => 'getEndOfFinancialYear',
        'registrationNumbers' => 'getRegistrationNumbers',
        'knownSince' => 'getKnownSince',
        'endDate' => 'getEndDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('isDeceased', $data ?? [], null);
        $this->setIfExists('deceasedDate', $data ?? [], null);
        $this->setIfExists('isSmoker', $data ?? [], null);
        $this->setIfExists('smokerEndDate', $data ?? [], null);
        $this->setIfExists('birthDate', $data ?? [], null);
        $this->setIfExists('language', $data ?? [], null);
        $this->setIfExists('organizationDateCreated', $data ?? [], null);
        $this->setIfExists('organizationDateClosed', $data ?? [], null);
        $this->setIfExists('numberOfEmployees', $data ?? [], null);
        $this->setIfExists('companyValue', $data ?? [], null);
        $this->setIfExists('annualGrowth', $data ?? [], null);
        $this->setIfExists('companyStage', $data ?? [], null);
        $this->setIfExists('revenue', $data ?? [], null);
        $this->setIfExists('netProfits', $data ?? [], null);
        $this->setIfExists('incorporationLocation', $data ?? [], null);
        $this->setIfExists('payroll', $data ?? [], null);
        $this->setIfExists('endOfFinancialYear', $data ?? [], null);
        $this->setIfExists('registrationNumbers', $data ?? [], null);
        $this->setIfExists('knownSince', $data ?? [], null);
        $this->setIfExists('endDate', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets isDeceased
     *
     * @return bool|null
     */
    public function getIsDeceased(): ?bool
    {
        return $this->container['isDeceased'];
    }

    /**
     * Sets isDeceased
     *
     * @param bool|null $isDeceased isDeceased
     *
     * @return $this
     */
    public function setIsDeceased(?bool $isDeceased): static
    {
        if (is_null($isDeceased)) {
            throw new InvalidArgumentException('non-nullable isDeceased cannot be null');
        }
        $this->container['isDeceased'] = $isDeceased;

        return $this;
    }

    /**
     * Gets deceasedDate
     *
     * @return \DateTime|null
     */
    public function getDeceasedDate(): ?\DateTime
    {
        return $this->container['deceasedDate'];
    }

    /**
     * Sets deceasedDate
     *
     * @param \DateTime|null $deceasedDate deceasedDate
     *
     * @return $this
     */
    public function setDeceasedDate(?\DateTime $deceasedDate): static
    {
        if (is_null($deceasedDate)) {
            array_push($this->openAPINullablesSetToNull, 'deceasedDate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deceasedDate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deceasedDate'] = $deceasedDate;

        return $this;
    }

    /**
     * Gets isSmoker
     *
     * @return bool|null
     */
    public function getIsSmoker(): ?bool
    {
        return $this->container['isSmoker'];
    }

    /**
     * Sets isSmoker
     *
     * @param bool|null $isSmoker isSmoker
     *
     * @return $this
     */
    public function setIsSmoker(?bool $isSmoker): static
    {
        if (is_null($isSmoker)) {
            throw new InvalidArgumentException('non-nullable isSmoker cannot be null');
        }
        $this->container['isSmoker'] = $isSmoker;

        return $this;
    }

    /**
     * Gets smokerEndDate
     *
     * @return \DateTime|null
     */
    public function getSmokerEndDate(): ?\DateTime
    {
        return $this->container['smokerEndDate'];
    }

    /**
     * Sets smokerEndDate
     *
     * @param \DateTime|null $smokerEndDate smokerEndDate
     *
     * @return $this
     */
    public function setSmokerEndDate(?\DateTime $smokerEndDate): static
    {
        if (is_null($smokerEndDate)) {
            array_push($this->openAPINullablesSetToNull, 'smokerEndDate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('smokerEndDate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['smokerEndDate'] = $smokerEndDate;

        return $this;
    }

    /**
     * Gets birthDate
     *
     * @return \DateTime|null
     */
    public function getBirthDate(): ?\DateTime
    {
        return $this->container['birthDate'];
    }

    /**
     * Sets birthDate
     *
     * @param \DateTime|null $birthDate birthDate
     *
     * @return $this
     */
    public function setBirthDate(?\DateTime $birthDate): static
    {
        if (is_null($birthDate)) {
            array_push($this->openAPINullablesSetToNull, 'birthDate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('birthDate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['birthDate'] = $birthDate;

        return $this;
    }

    /**
     * Gets language
     *
     * @return int|null
     */
    public function getLanguage(): ?int
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param int|null $language Refer to the values provided by the FieldValue endpoint with fieldName CONTACT_LANG.
     *
     * @return $this
     */
    public function setLanguage(?int $language): static
    {
        if (is_null($language)) {
            array_push($this->openAPINullablesSetToNull, 'language');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('language', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets organizationDateCreated
     *
     * @return \DateTime|null
     */
    public function getOrganizationDateCreated(): ?\DateTime
    {
        return $this->container['organizationDateCreated'];
    }

    /**
     * Sets organizationDateCreated
     *
     * @param \DateTime|null $organizationDateCreated organizationDateCreated
     *
     * @return $this
     */
    public function setOrganizationDateCreated(?\DateTime $organizationDateCreated): static
    {
        if (is_null($organizationDateCreated)) {
            array_push($this->openAPINullablesSetToNull, 'organizationDateCreated');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('organizationDateCreated', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['organizationDateCreated'] = $organizationDateCreated;

        return $this;
    }

    /**
     * Gets organizationDateClosed
     *
     * @return \DateTime|null
     */
    public function getOrganizationDateClosed(): ?\DateTime
    {
        return $this->container['organizationDateClosed'];
    }

    /**
     * Sets organizationDateClosed
     *
     * @param \DateTime|null $organizationDateClosed organizationDateClosed
     *
     * @return $this
     */
    public function setOrganizationDateClosed(?\DateTime $organizationDateClosed): static
    {
        if (is_null($organizationDateClosed)) {
            array_push($this->openAPINullablesSetToNull, 'organizationDateClosed');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('organizationDateClosed', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['organizationDateClosed'] = $organizationDateClosed;

        return $this;
    }

    /**
     * Gets numberOfEmployees
     *
     * @return int|null
     */
    public function getNumberOfEmployees(): ?int
    {
        return $this->container['numberOfEmployees'];
    }

    /**
     * Sets numberOfEmployees
     *
     * @param int|null $numberOfEmployees Refer to the values provided by the FieldValue endpoint with fieldName ORG_NB_EMPLOYEE.
     *
     * @return $this
     */
    public function setNumberOfEmployees(?int $numberOfEmployees): static
    {
        if (is_null($numberOfEmployees)) {
            array_push($this->openAPINullablesSetToNull, 'numberOfEmployees');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('numberOfEmployees', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['numberOfEmployees'] = $numberOfEmployees;

        return $this;
    }

    /**
     * Gets companyValue
     *
     * @return int|null
     */
    public function getCompanyValue(): ?int
    {
        return $this->container['companyValue'];
    }

    /**
     * Sets companyValue
     *
     * @param int|null $companyValue Refer to the values provided by the FieldValue endpoint with fieldName ORG_COMPANY_VALUE.
     *
     * @return $this
     */
    public function setCompanyValue(?int $companyValue): static
    {
        if (is_null($companyValue)) {
            array_push($this->openAPINullablesSetToNull, 'companyValue');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('companyValue', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['companyValue'] = $companyValue;

        return $this;
    }

    /**
     * Gets annualGrowth
     *
     * @return int|null
     */
    public function getAnnualGrowth(): ?int
    {
        return $this->container['annualGrowth'];
    }

    /**
     * Sets annualGrowth
     *
     * @param int|null $annualGrowth Refer to the values provided by the FieldValue endpoint with fieldName ORG_ANNUAL_GROWTH.
     *
     * @return $this
     */
    public function setAnnualGrowth(?int $annualGrowth): static
    {
        if (is_null($annualGrowth)) {
            array_push($this->openAPINullablesSetToNull, 'annualGrowth');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('annualGrowth', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['annualGrowth'] = $annualGrowth;

        return $this;
    }

    /**
     * Gets companyStage
     *
     * @return int|null
     */
    public function getCompanyStage(): ?int
    {
        return $this->container['companyStage'];
    }

    /**
     * Sets companyStage
     *
     * @param int|null $companyStage Refer to the values provided by the FieldValue endpoint with fieldName ORG_COMPANY_STAGE.
     *
     * @return $this
     */
    public function setCompanyStage(?int $companyStage): static
    {
        if (is_null($companyStage)) {
            array_push($this->openAPINullablesSetToNull, 'companyStage');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('companyStage', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['companyStage'] = $companyStage;

        return $this;
    }

    /**
     * Gets revenue
     *
     * @return \Equisoft\SDK\EquisoftConnect\Model\ContactsCreateRevenuePayload|null
     */
    public function getRevenue(): ?\Equisoft\SDK\EquisoftConnect\Model\ContactsCreateRevenuePayload
    {
        return $this->container['revenue'];
    }

    /**
     * Sets revenue
     *
     * @param \Equisoft\SDK\EquisoftConnect\Model\ContactsCreateRevenuePayload|null $revenue revenue
     *
     * @return $this
     */
    public function setRevenue(?\Equisoft\SDK\EquisoftConnect\Model\ContactsCreateRevenuePayload $revenue): static
    {
        if (is_null($revenue)) {
            array_push($this->openAPINullablesSetToNull, 'revenue');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('revenue', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['revenue'] = $revenue;

        return $this;
    }

    /**
     * Gets netProfits
     *
     * @return int|null
     */
    public function getNetProfits(): ?int
    {
        return $this->container['netProfits'];
    }

    /**
     * Sets netProfits
     *
     * @param int|null $netProfits Refer to the values provided by the FieldValue endpoint with fieldName ORG_NET_PROFIT.
     *
     * @return $this
     */
    public function setNetProfits(?int $netProfits): static
    {
        if (is_null($netProfits)) {
            array_push($this->openAPINullablesSetToNull, 'netProfits');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('netProfits', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['netProfits'] = $netProfits;

        return $this;
    }

    /**
     * Gets incorporationLocation
     *
     * @return int|null
     */
    public function getIncorporationLocation(): ?int
    {
        return $this->container['incorporationLocation'];
    }

    /**
     * Sets incorporationLocation
     *
     * @param int|null $incorporationLocation Refer to the values provided by the FieldValue endpoint with fieldName ORG_INCORPORATION_LOCATION.
     *
     * @return $this
     */
    public function setIncorporationLocation(?int $incorporationLocation): static
    {
        if (is_null($incorporationLocation)) {
            array_push($this->openAPINullablesSetToNull, 'incorporationLocation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('incorporationLocation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['incorporationLocation'] = $incorporationLocation;

        return $this;
    }

    /**
     * Gets payroll
     *
     * @return int|null
     */
    public function getPayroll(): ?int
    {
        return $this->container['payroll'];
    }

    /**
     * Sets payroll
     *
     * @param int|null $payroll Refer to the values provided by the FieldValue endpoint with fieldName ORG_PAYROLL.
     *
     * @return $this
     */
    public function setPayroll(?int $payroll): static
    {
        if (is_null($payroll)) {
            array_push($this->openAPINullablesSetToNull, 'payroll');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('payroll', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['payroll'] = $payroll;

        return $this;
    }

    /**
     * Gets endOfFinancialYear
     *
     * @return string|null
     */
    public function getEndOfFinancialYear(): ?string
    {
        return $this->container['endOfFinancialYear'];
    }

    /**
     * Sets endOfFinancialYear
     *
     * @param string|null $endOfFinancialYear Only support full month name in English in uppercase (JANUARY, FEBRUARY, etc.)
     *
     * @return $this
     */
    public function setEndOfFinancialYear(?string $endOfFinancialYear): static
    {
        if (is_null($endOfFinancialYear)) {
            array_push($this->openAPINullablesSetToNull, 'endOfFinancialYear');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('endOfFinancialYear', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['endOfFinancialYear'] = $endOfFinancialYear;

        return $this;
    }

    /**
     * Gets registrationNumbers
     *
     * @return \Equisoft\SDK\EquisoftConnect\Model\ContactsCreateRegistrationNumbersPayload|null
     */
    public function getRegistrationNumbers(): ?\Equisoft\SDK\EquisoftConnect\Model\ContactsCreateRegistrationNumbersPayload
    {
        return $this->container['registrationNumbers'];
    }

    /**
     * Sets registrationNumbers
     *
     * @param \Equisoft\SDK\EquisoftConnect\Model\ContactsCreateRegistrationNumbersPayload|null $registrationNumbers registrationNumbers
     *
     * @return $this
     */
    public function setRegistrationNumbers(?\Equisoft\SDK\EquisoftConnect\Model\ContactsCreateRegistrationNumbersPayload $registrationNumbers): static
    {
        if (is_null($registrationNumbers)) {
            array_push($this->openAPINullablesSetToNull, 'registrationNumbers');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('registrationNumbers', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['registrationNumbers'] = $registrationNumbers;

        return $this;
    }

    /**
     * Gets knownSince
     *
     * @return \DateTime|null
     */
    public function getKnownSince(): ?\DateTime
    {
        return $this->container['knownSince'];
    }

    /**
     * Sets knownSince
     *
     * @param \DateTime|null $knownSince knownSince
     *
     * @return $this
     */
    public function setKnownSince(?\DateTime $knownSince): static
    {
        if (is_null($knownSince)) {
            array_push($this->openAPINullablesSetToNull, 'knownSince');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('knownSince', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['knownSince'] = $knownSince;

        return $this;
    }

    /**
     * Gets endDate
     *
     * @return \DateTime|null
     */
    public function getEndDate(): ?\DateTime
    {
        return $this->container['endDate'];
    }

    /**
     * Sets endDate
     *
     * @param \DateTime|null $endDate endDate
     *
     * @return $this
     */
    public function setEndDate(?\DateTime $endDate): static
    {
        if (is_null($endDate)) {
            array_push($this->openAPINullablesSetToNull, 'endDate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('endDate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['endDate'] = $endDate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


