<?php
/**
 * InternalNotesNote
 *
 * PHP version 8.1
 *
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-equisoft1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Equisoft\SDK\EquisoftConnect\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Equisoft\SDK\EquisoftConnect\ObjectSerializer;

/**
 * InternalNotesNote Class Doc Comment
 *
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class InternalNotesNote implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'internalNotes.Note';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'id' => 'int',
        'author' => '\Equisoft\SDK\EquisoftConnect\Model\InternalNotesAuthor',
        'firstRevisionCreatedAt' => '\DateTime',
        'accessRights' => '\Equisoft\SDK\EquisoftConnect\Model\AccessRights',
        'currentRevision' => '\Equisoft\SDK\EquisoftConnect\Model\InternalNotesNoteRevision',
        'previousRevisions' => '\Equisoft\SDK\EquisoftConnect\Model\InternalNotesNoteRevision[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'id' => null,
        'author' => null,
        'firstRevisionCreatedAt' => 'date-time',
        'accessRights' => null,
        'currentRevision' => null,
        'previousRevisions' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'id' => true,
        'author' => true,
        'firstRevisionCreatedAt' => true,
        'accessRights' => false,
        'currentRevision' => true,
        'previousRevisions' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'author' => 'author',
        'firstRevisionCreatedAt' => 'firstRevisionCreatedAt',
        'accessRights' => 'accessRights',
        'currentRevision' => 'currentRevision',
        'previousRevisions' => 'previousRevisions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'author' => 'setAuthor',
        'firstRevisionCreatedAt' => 'setFirstRevisionCreatedAt',
        'accessRights' => 'setAccessRights',
        'currentRevision' => 'setCurrentRevision',
        'previousRevisions' => 'setPreviousRevisions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'author' => 'getAuthor',
        'firstRevisionCreatedAt' => 'getFirstRevisionCreatedAt',
        'accessRights' => 'getAccessRights',
        'currentRevision' => 'getCurrentRevision',
        'previousRevisions' => 'getPreviousRevisions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('author', $data ?? [], null);
        $this->setIfExists('firstRevisionCreatedAt', $data ?? [], null);
        $this->setIfExists('accessRights', $data ?? [], null);
        $this->setIfExists('currentRevision', $data ?? [], null);
        $this->setIfExists('previousRevisions', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['author'] === null) {
            $invalidProperties[] = "'author' can't be null";
        }
        if ($this->container['firstRevisionCreatedAt'] === null) {
            $invalidProperties[] = "'firstRevisionCreatedAt' can't be null";
        }
        if ($this->container['accessRights'] === null) {
            $invalidProperties[] = "'accessRights' can't be null";
        }
        if ($this->container['currentRevision'] === null) {
            $invalidProperties[] = "'currentRevision' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id Unique numerical identifier.
     *
     * @return $this
     */
    public function setId(?int $id): static
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets author
     *
     * @return \Equisoft\SDK\EquisoftConnect\Model\InternalNotesAuthor|null
     */
    public function getAuthor(): ?\Equisoft\SDK\EquisoftConnect\Model\InternalNotesAuthor
    {
        return $this->container['author'];
    }

    /**
     * Sets author
     *
     * @param \Equisoft\SDK\EquisoftConnect\Model\InternalNotesAuthor|null $author author
     *
     * @return $this
     */
    public function setAuthor(?\Equisoft\SDK\EquisoftConnect\Model\InternalNotesAuthor $author): static
    {
        if (is_null($author)) {
            array_push($this->openAPINullablesSetToNull, 'author');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('author', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['author'] = $author;

        return $this;
    }

    /**
     * Gets firstRevisionCreatedAt
     *
     * @return \DateTime|null
     */
    public function getFirstRevisionCreatedAt(): ?\DateTime
    {
        return $this->container['firstRevisionCreatedAt'];
    }

    /**
     * Sets firstRevisionCreatedAt
     *
     * @param \DateTime|null $firstRevisionCreatedAt First revision created at.
     *
     * @return $this
     */
    public function setFirstRevisionCreatedAt(?\DateTime $firstRevisionCreatedAt): static
    {
        if (is_null($firstRevisionCreatedAt)) {
            array_push($this->openAPINullablesSetToNull, 'firstRevisionCreatedAt');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('firstRevisionCreatedAt', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['firstRevisionCreatedAt'] = $firstRevisionCreatedAt;

        return $this;
    }

    /**
     * Gets accessRights
     *
     * @return \Equisoft\SDK\EquisoftConnect\Model\AccessRights
     */
    public function getAccessRights(): \Equisoft\SDK\EquisoftConnect\Model\AccessRights
    {
        return $this->container['accessRights'];
    }

    /**
     * Sets accessRights
     *
     * @param \Equisoft\SDK\EquisoftConnect\Model\AccessRights $accessRights accessRights
     *
     * @return $this
     */
    public function setAccessRights(\Equisoft\SDK\EquisoftConnect\Model\AccessRights $accessRights): static
    {
        if (is_null($accessRights)) {
            throw new InvalidArgumentException('non-nullable accessRights cannot be null');
        }
        $this->container['accessRights'] = $accessRights;

        return $this;
    }

    /**
     * Gets currentRevision
     *
     * @return \Equisoft\SDK\EquisoftConnect\Model\InternalNotesNoteRevision|null
     */
    public function getCurrentRevision(): ?\Equisoft\SDK\EquisoftConnect\Model\InternalNotesNoteRevision
    {
        return $this->container['currentRevision'];
    }

    /**
     * Sets currentRevision
     *
     * @param \Equisoft\SDK\EquisoftConnect\Model\InternalNotesNoteRevision|null $currentRevision currentRevision
     *
     * @return $this
     */
    public function setCurrentRevision(?\Equisoft\SDK\EquisoftConnect\Model\InternalNotesNoteRevision $currentRevision): static
    {
        if (is_null($currentRevision)) {
            array_push($this->openAPINullablesSetToNull, 'currentRevision');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('currentRevision', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['currentRevision'] = $currentRevision;

        return $this;
    }

    /**
     * Gets previousRevisions
     *
     * @return \Equisoft\SDK\EquisoftConnect\Model\InternalNotesNoteRevision[]|null
     */
    public function getPreviousRevisions(): ?array
    {
        return $this->container['previousRevisions'];
    }

    /**
     * Sets previousRevisions
     *
     * @param \Equisoft\SDK\EquisoftConnect\Model\InternalNotesNoteRevision[]|null $previousRevisions List of previous revisions.
     *
     * @return $this
     */
    public function setPreviousRevisions(?array $previousRevisions): static
    {
        if (is_null($previousRevisions)) {
            throw new InvalidArgumentException('non-nullable previousRevisions cannot be null');
        }
        $this->container['previousRevisions'] = $previousRevisions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


