<?php
/**
 * LegacyContactContact
 *
 * PHP version 8.1
 *
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-equisoft1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Equisoft\SDK\EquisoftConnect\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Equisoft\SDK\EquisoftConnect\ObjectSerializer;

/**
 * LegacyContactContact Class Doc Comment
 *
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class LegacyContactContact implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'legacy.contact.Contact';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'id' => 'string',
        'uuid' => 'string',
        'typeContact' => 'string',
        'indOrg' => 'string',
        'displayName' => 'string',
        'firstName' => 'string',
        'nickname' => 'string',
        'middleName' => 'string',
        'lastName' => 'string',
        'corporationName' => 'string',
        'corporationNameLine2' => 'string',
        'rank' => 'string',
        'facebookLink' => 'string',
        'twitterLink' => 'string',
        'linkedinLink' => 'string',
        'avatar' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'id' => null,
        'uuid' => null,
        'typeContact' => null,
        'indOrg' => null,
        'displayName' => null,
        'firstName' => null,
        'nickname' => null,
        'middleName' => null,
        'lastName' => null,
        'corporationName' => null,
        'corporationNameLine2' => null,
        'rank' => null,
        'facebookLink' => null,
        'twitterLink' => null,
        'linkedinLink' => null,
        'avatar' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'id' => false,
        'uuid' => false,
        'typeContact' => false,
        'indOrg' => false,
        'displayName' => false,
        'firstName' => false,
        'nickname' => false,
        'middleName' => false,
        'lastName' => false,
        'corporationName' => false,
        'corporationNameLine2' => false,
        'rank' => false,
        'facebookLink' => false,
        'twitterLink' => false,
        'linkedinLink' => false,
        'avatar' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'uuid' => 'uuid',
        'typeContact' => 'typeContact',
        'indOrg' => 'indOrg',
        'displayName' => 'displayName',
        'firstName' => 'firstName',
        'nickname' => 'nickname',
        'middleName' => 'middleName',
        'lastName' => 'lastName',
        'corporationName' => 'corporationName',
        'corporationNameLine2' => 'corporationNameLine2',
        'rank' => 'rank',
        'facebookLink' => 'facebookLink',
        'twitterLink' => 'twitterLink',
        'linkedinLink' => 'linkedinLink',
        'avatar' => 'avatar'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'uuid' => 'setUuid',
        'typeContact' => 'setTypeContact',
        'indOrg' => 'setIndOrg',
        'displayName' => 'setDisplayName',
        'firstName' => 'setFirstName',
        'nickname' => 'setNickname',
        'middleName' => 'setMiddleName',
        'lastName' => 'setLastName',
        'corporationName' => 'setCorporationName',
        'corporationNameLine2' => 'setCorporationNameLine2',
        'rank' => 'setRank',
        'facebookLink' => 'setFacebookLink',
        'twitterLink' => 'setTwitterLink',
        'linkedinLink' => 'setLinkedinLink',
        'avatar' => 'setAvatar'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'uuid' => 'getUuid',
        'typeContact' => 'getTypeContact',
        'indOrg' => 'getIndOrg',
        'displayName' => 'getDisplayName',
        'firstName' => 'getFirstName',
        'nickname' => 'getNickname',
        'middleName' => 'getMiddleName',
        'lastName' => 'getLastName',
        'corporationName' => 'getCorporationName',
        'corporationNameLine2' => 'getCorporationNameLine2',
        'rank' => 'getRank',
        'facebookLink' => 'getFacebookLink',
        'twitterLink' => 'getTwitterLink',
        'linkedinLink' => 'getLinkedinLink',
        'avatar' => 'getAvatar'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('uuid', $data ?? [], null);
        $this->setIfExists('typeContact', $data ?? [], null);
        $this->setIfExists('indOrg', $data ?? [], null);
        $this->setIfExists('displayName', $data ?? [], null);
        $this->setIfExists('firstName', $data ?? [], null);
        $this->setIfExists('nickname', $data ?? [], null);
        $this->setIfExists('middleName', $data ?? [], null);
        $this->setIfExists('lastName', $data ?? [], null);
        $this->setIfExists('corporationName', $data ?? [], null);
        $this->setIfExists('corporationNameLine2', $data ?? [], null);
        $this->setIfExists('rank', $data ?? [], null);
        $this->setIfExists('facebookLink', $data ?? [], null);
        $this->setIfExists('twitterLink', $data ?? [], null);
        $this->setIfExists('linkedinLink', $data ?? [], null);
        $this->setIfExists('avatar', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId(): ?string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id Unique id.
     *
     * @return $this
     */
    public function setId(?string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets uuid
     *
     * @return string|null
     */
    public function getUuid(): ?string
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param string|null $uuid Contact UUID.
     *
     * @return $this
     */
    public function setUuid(?string $uuid): static
    {
        if (is_null($uuid)) {
            throw new InvalidArgumentException('non-nullable uuid cannot be null');
        }
        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets typeContact
     *
     * @return string|null
     */
    public function getTypeContact(): ?string
    {
        return $this->container['typeContact'];
    }

    /**
     * Sets typeContact
     *
     * @param string|null $typeContact Type of the contact.
     *
     * @return $this
     */
    public function setTypeContact(?string $typeContact): static
    {
        if (is_null($typeContact)) {
            throw new InvalidArgumentException('non-nullable typeContact cannot be null');
        }
        $this->container['typeContact'] = $typeContact;

        return $this;
    }

    /**
     * Gets indOrg
     *
     * @return string|null
     */
    public function getIndOrg(): ?string
    {
        return $this->container['indOrg'];
    }

    /**
     * Sets indOrg
     *
     * @param string|null $indOrg Type INDIVIDUAL OR ORGANIZATION.
     *
     * @return $this
     */
    public function setIndOrg(?string $indOrg): static
    {
        if (is_null($indOrg)) {
            throw new InvalidArgumentException('non-nullable indOrg cannot be null');
        }
        $this->container['indOrg'] = $indOrg;

        return $this;
    }

    /**
     * Gets displayName
     *
     * @return string|null
     */
    public function getDisplayName(): ?string
    {
        return $this->container['displayName'];
    }

    /**
     * Sets displayName
     *
     * @param string|null $displayName Display name of the contact.
     *
     * @return $this
     */
    public function setDisplayName(?string $displayName): static
    {
        if (is_null($displayName)) {
            throw new InvalidArgumentException('non-nullable displayName cannot be null');
        }
        $this->container['displayName'] = $displayName;

        return $this;
    }

    /**
     * Gets firstName
     *
     * @return string|null
     */
    public function getFirstName(): ?string
    {
        return $this->container['firstName'];
    }

    /**
     * Sets firstName
     *
     * @param string|null $firstName First name of the contact.
     *
     * @return $this
     */
    public function setFirstName(?string $firstName): static
    {
        if (is_null($firstName)) {
            throw new InvalidArgumentException('non-nullable firstName cannot be null');
        }
        $this->container['firstName'] = $firstName;

        return $this;
    }

    /**
     * Gets nickname
     *
     * @return string|null
     */
    public function getNickname(): ?string
    {
        return $this->container['nickname'];
    }

    /**
     * Sets nickname
     *
     * @param string|null $nickname Nickname of the contact.
     *
     * @return $this
     */
    public function setNickname(?string $nickname): static
    {
        if (is_null($nickname)) {
            throw new InvalidArgumentException('non-nullable nickname cannot be null');
        }
        $this->container['nickname'] = $nickname;

        return $this;
    }

    /**
     * Gets middleName
     *
     * @return string|null
     */
    public function getMiddleName(): ?string
    {
        return $this->container['middleName'];
    }

    /**
     * Sets middleName
     *
     * @param string|null $middleName Middle name of the contact.
     *
     * @return $this
     */
    public function setMiddleName(?string $middleName): static
    {
        if (is_null($middleName)) {
            throw new InvalidArgumentException('non-nullable middleName cannot be null');
        }
        $this->container['middleName'] = $middleName;

        return $this;
    }

    /**
     * Gets lastName
     *
     * @return string|null
     */
    public function getLastName(): ?string
    {
        return $this->container['lastName'];
    }

    /**
     * Sets lastName
     *
     * @param string|null $lastName Last name of the contact.
     *
     * @return $this
     */
    public function setLastName(?string $lastName): static
    {
        if (is_null($lastName)) {
            throw new InvalidArgumentException('non-nullable lastName cannot be null');
        }
        $this->container['lastName'] = $lastName;

        return $this;
    }

    /**
     * Gets corporationName
     *
     * @return string|null
     */
    public function getCorporationName(): ?string
    {
        return $this->container['corporationName'];
    }

    /**
     * Sets corporationName
     *
     * @param string|null $corporationName First line of corporation name (Organization).
     *
     * @return $this
     */
    public function setCorporationName(?string $corporationName): static
    {
        if (is_null($corporationName)) {
            throw new InvalidArgumentException('non-nullable corporationName cannot be null');
        }
        $this->container['corporationName'] = $corporationName;

        return $this;
    }

    /**
     * Gets corporationNameLine2
     *
     * @return string|null
     */
    public function getCorporationNameLine2(): ?string
    {
        return $this->container['corporationNameLine2'];
    }

    /**
     * Sets corporationNameLine2
     *
     * @param string|null $corporationNameLine2 Second line of corporation name (Organization).
     *
     * @return $this
     */
    public function setCorporationNameLine2(?string $corporationNameLine2): static
    {
        if (is_null($corporationNameLine2)) {
            throw new InvalidArgumentException('non-nullable corporationNameLine2 cannot be null');
        }
        $this->container['corporationNameLine2'] = $corporationNameLine2;

        return $this;
    }

    /**
     * Gets rank
     *
     * @return string|null
     */
    public function getRank(): ?string
    {
        return $this->container['rank'];
    }

    /**
     * Sets rank
     *
     * @param string|null $rank Rank of the contact. (Industrial Alliance only).
     *
     * @return $this
     */
    public function setRank(?string $rank): static
    {
        if (is_null($rank)) {
            throw new InvalidArgumentException('non-nullable rank cannot be null');
        }
        $this->container['rank'] = $rank;

        return $this;
    }

    /**
     * Gets facebookLink
     *
     * @return string|null
     */
    public function getFacebookLink(): ?string
    {
        return $this->container['facebookLink'];
    }

    /**
     * Sets facebookLink
     *
     * @param string|null $facebookLink Facebook link.
     *
     * @return $this
     */
    public function setFacebookLink(?string $facebookLink): static
    {
        if (is_null($facebookLink)) {
            throw new InvalidArgumentException('non-nullable facebookLink cannot be null');
        }
        $this->container['facebookLink'] = $facebookLink;

        return $this;
    }

    /**
     * Gets twitterLink
     *
     * @return string|null
     */
    public function getTwitterLink(): ?string
    {
        return $this->container['twitterLink'];
    }

    /**
     * Sets twitterLink
     *
     * @param string|null $twitterLink Twitter link.
     *
     * @return $this
     */
    public function setTwitterLink(?string $twitterLink): static
    {
        if (is_null($twitterLink)) {
            throw new InvalidArgumentException('non-nullable twitterLink cannot be null');
        }
        $this->container['twitterLink'] = $twitterLink;

        return $this;
    }

    /**
     * Gets linkedinLink
     *
     * @return string|null
     */
    public function getLinkedinLink(): ?string
    {
        return $this->container['linkedinLink'];
    }

    /**
     * Sets linkedinLink
     *
     * @param string|null $linkedinLink LinkedIn link.
     *
     * @return $this
     */
    public function setLinkedinLink(?string $linkedinLink): static
    {
        if (is_null($linkedinLink)) {
            throw new InvalidArgumentException('non-nullable linkedinLink cannot be null');
        }
        $this->container['linkedinLink'] = $linkedinLink;

        return $this;
    }

    /**
     * Gets avatar
     *
     * @return int|null
     */
    public function getAvatar(): ?int
    {
        return $this->container['avatar'];
    }

    /**
     * Sets avatar
     *
     * @param int|null $avatar Avatar.
     *
     * @return $this
     */
    public function setAvatar(?int $avatar): static
    {
        if (is_null($avatar)) {
            throw new InvalidArgumentException('non-nullable avatar cannot be null');
        }
        $this->container['avatar'] = $avatar;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


