<?php
/**
 * MovementMovement
 *
 * PHP version 8.1
 *
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-equisoft1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Equisoft\SDK\EquisoftConnect\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Equisoft\SDK\EquisoftConnect\ObjectSerializer;

/**
 * MovementMovement Class Doc Comment
 *
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class MovementMovement implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = 'type';
    public const DISCRIMINATOR_MAP = [
        "CLIENTBASE_USING_DISTLIST" => "MovementClientBaseUsingDistributionListMovement",
        "CLIENTBASE_USING_FILE" => "MovementClientBaseUsingFileMovement",
        "COPY" => "MovementCopyMovement",
        "MOVE" => "MovementMoveMovement",
    ];

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'movement.Movement';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'type' => '\Equisoft\SDK\EquisoftConnect\Model\MovementMovementType',
        'id' => 'int',
        'status' => 'string',
        'availableAction' => 'string',
        'scheduledDate' => 'string',
        'processedDate' => 'string',
        'addedDate' => 'string',
        'addedBy' => '\Equisoft\SDK\EquisoftConnect\Model\MovementUser',
        'cancelledDate' => 'string',
        'cancelledBy' => '\Equisoft\SDK\EquisoftConnect\Model\MovementUser',
        'sourceDatabase' => '\Equisoft\SDK\EquisoftConnect\Model\MovementDatabase',
        'destinationDatabase' => '\Equisoft\SDK\EquisoftConnect\Model\MovementDatabase',
        'users' => '\Equisoft\SDK\EquisoftConnect\Model\MovementUser[]',
        'userTuples' => '\Equisoft\SDK\EquisoftConnect\Model\MovementUserTuple[]',
        'sourceUser' => '\Equisoft\SDK\EquisoftConnect\Model\MovementUser',
        'sourceDistributionList' => '\Equisoft\SDK\EquisoftConnect\Model\MovementDistributionList',
        'destinationUser' => '\Equisoft\SDK\EquisoftConnect\Model\MovementUser',
        'transferOption' => '\Equisoft\SDK\EquisoftConnect\Model\MovementTransferOption',
        'capsil' => 'bool',
        'univeris' => 'bool',
        'dataphile' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'type' => null,
        'id' => null,
        'status' => null,
        'availableAction' => null,
        'scheduledDate' => null,
        'processedDate' => null,
        'addedDate' => null,
        'addedBy' => null,
        'cancelledDate' => null,
        'cancelledBy' => null,
        'sourceDatabase' => null,
        'destinationDatabase' => null,
        'users' => null,
        'userTuples' => null,
        'sourceUser' => null,
        'sourceDistributionList' => null,
        'destinationUser' => null,
        'transferOption' => null,
        'capsil' => null,
        'univeris' => null,
        'dataphile' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'type' => false,
        'id' => false,
        'status' => false,
        'availableAction' => false,
        'scheduledDate' => true,
        'processedDate' => true,
        'addedDate' => true,
        'addedBy' => true,
        'cancelledDate' => true,
        'cancelledBy' => true,
        'sourceDatabase' => false,
        'destinationDatabase' => false,
        'users' => false,
        'userTuples' => false,
        'sourceUser' => false,
        'sourceDistributionList' => false,
        'destinationUser' => false,
        'transferOption' => false,
        'capsil' => false,
        'univeris' => false,
        'dataphile' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'type' => 'type',
        'id' => 'id',
        'status' => 'status',
        'availableAction' => 'availableAction',
        'scheduledDate' => 'scheduledDate',
        'processedDate' => 'processedDate',
        'addedDate' => 'addedDate',
        'addedBy' => 'addedBy',
        'cancelledDate' => 'cancelledDate',
        'cancelledBy' => 'cancelledBy',
        'sourceDatabase' => 'sourceDatabase',
        'destinationDatabase' => 'destinationDatabase',
        'users' => 'users',
        'userTuples' => 'userTuples',
        'sourceUser' => 'sourceUser',
        'sourceDistributionList' => 'sourceDistributionList',
        'destinationUser' => 'destinationUser',
        'transferOption' => 'transferOption',
        'capsil' => 'capsil',
        'univeris' => 'univeris',
        'dataphile' => 'dataphile'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'type' => 'setType',
        'id' => 'setId',
        'status' => 'setStatus',
        'availableAction' => 'setAvailableAction',
        'scheduledDate' => 'setScheduledDate',
        'processedDate' => 'setProcessedDate',
        'addedDate' => 'setAddedDate',
        'addedBy' => 'setAddedBy',
        'cancelledDate' => 'setCancelledDate',
        'cancelledBy' => 'setCancelledBy',
        'sourceDatabase' => 'setSourceDatabase',
        'destinationDatabase' => 'setDestinationDatabase',
        'users' => 'setUsers',
        'userTuples' => 'setUserTuples',
        'sourceUser' => 'setSourceUser',
        'sourceDistributionList' => 'setSourceDistributionList',
        'destinationUser' => 'setDestinationUser',
        'transferOption' => 'setTransferOption',
        'capsil' => 'setCapsil',
        'univeris' => 'setUniveris',
        'dataphile' => 'setDataphile'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'type' => 'getType',
        'id' => 'getId',
        'status' => 'getStatus',
        'availableAction' => 'getAvailableAction',
        'scheduledDate' => 'getScheduledDate',
        'processedDate' => 'getProcessedDate',
        'addedDate' => 'getAddedDate',
        'addedBy' => 'getAddedBy',
        'cancelledDate' => 'getCancelledDate',
        'cancelledBy' => 'getCancelledBy',
        'sourceDatabase' => 'getSourceDatabase',
        'destinationDatabase' => 'getDestinationDatabase',
        'users' => 'getUsers',
        'userTuples' => 'getUserTuples',
        'sourceUser' => 'getSourceUser',
        'sourceDistributionList' => 'getSourceDistributionList',
        'destinationUser' => 'getDestinationUser',
        'transferOption' => 'getTransferOption',
        'capsil' => 'getCapsil',
        'univeris' => 'getUniveris',
        'dataphile' => 'getDataphile'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const TYPE_CLIENTBASE_USING_DISTLIST = 'CLIENTBASE_USING_DISTLIST';
    public const TYPE_CLIENTBASE_USING_FILE = 'CLIENTBASE_USING_FILE';
    public const TYPE_COPY = 'COPY';
    public const TYPE_MOVE = 'MOVE';

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        // Initialize discriminator property with the model name.
        $this->container['type'] = static::$openAPIModelName;

        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('availableAction', $data ?? [], null);
        $this->setIfExists('scheduledDate', $data ?? [], null);
        $this->setIfExists('processedDate', $data ?? [], null);
        $this->setIfExists('addedDate', $data ?? [], null);
        $this->setIfExists('addedBy', $data ?? [], null);
        $this->setIfExists('cancelledDate', $data ?? [], null);
        $this->setIfExists('cancelledBy', $data ?? [], null);
        $this->setIfExists('sourceDatabase', $data ?? [], null);
        $this->setIfExists('destinationDatabase', $data ?? [], null);
        $this->setIfExists('users', $data ?? [], null);
        $this->setIfExists('userTuples', $data ?? [], null);
        $this->setIfExists('sourceUser', $data ?? [], null);
        $this->setIfExists('sourceDistributionList', $data ?? [], null);
        $this->setIfExists('destinationUser', $data ?? [], null);
        $this->setIfExists('transferOption', $data ?? [], null);
        $this->setIfExists('capsil', $data ?? [], null);
        $this->setIfExists('univeris', $data ?? [], null);
        $this->setIfExists('dataphile', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['sourceDatabase'] === null) {
            $invalidProperties[] = "'sourceDatabase' can't be null";
        }
        if ($this->container['destinationDatabase'] === null) {
            $invalidProperties[] = "'destinationDatabase' can't be null";
        }
        if ($this->container['users'] === null) {
            $invalidProperties[] = "'users' can't be null";
        }
        if ($this->container['userTuples'] === null) {
            $invalidProperties[] = "'userTuples' can't be null";
        }
        if ($this->container['sourceUser'] === null) {
            $invalidProperties[] = "'sourceUser' can't be null";
        }
        if ($this->container['destinationUser'] === null) {
            $invalidProperties[] = "'destinationUser' can't be null";
        }
        if ($this->container['transferOption'] === null) {
            $invalidProperties[] = "'transferOption' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return \Equisoft\SDK\EquisoftConnect\Model\MovementMovementType|null
     */
    public function getType(): ?\Equisoft\SDK\EquisoftConnect\Model\MovementMovementType
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \Equisoft\SDK\EquisoftConnect\Model\MovementMovementType|null $type type
     *
     * @return $this
     */
    public function setType(?\Equisoft\SDK\EquisoftConnect\Model\MovementMovementType $type): static
    {
        if (is_null($type)) {
            throw new InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id Unique numerical identifier.
     *
     * @return $this
     */
    public function setId(?int $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus(): ?string
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status Movement status.
     *
     * @return $this
     */
    public function setStatus(?string $status): static
    {
        if (is_null($status)) {
            throw new InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets availableAction
     *
     * @return string|null
     */
    public function getAvailableAction(): ?string
    {
        return $this->container['availableAction'];
    }

    /**
     * Sets availableAction
     *
     * @param string|null $availableAction Available action.
     *
     * @return $this
     */
    public function setAvailableAction(?string $availableAction): static
    {
        if (is_null($availableAction)) {
            throw new InvalidArgumentException('non-nullable availableAction cannot be null');
        }
        $this->container['availableAction'] = $availableAction;

        return $this;
    }

    /**
     * Gets scheduledDate
     *
     * @return string|null
     */
    public function getScheduledDate(): ?string
    {
        return $this->container['scheduledDate'];
    }

    /**
     * Sets scheduledDate
     *
     * @param string|null $scheduledDate Scheduled date.
     *
     * @return $this
     */
    public function setScheduledDate(?string $scheduledDate): static
    {
        if (is_null($scheduledDate)) {
            array_push($this->openAPINullablesSetToNull, 'scheduledDate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('scheduledDate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['scheduledDate'] = $scheduledDate;

        return $this;
    }

    /**
     * Gets processedDate
     *
     * @return string|null
     */
    public function getProcessedDate(): ?string
    {
        return $this->container['processedDate'];
    }

    /**
     * Sets processedDate
     *
     * @param string|null $processedDate Processed date.
     *
     * @return $this
     */
    public function setProcessedDate(?string $processedDate): static
    {
        if (is_null($processedDate)) {
            array_push($this->openAPINullablesSetToNull, 'processedDate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('processedDate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['processedDate'] = $processedDate;

        return $this;
    }

    /**
     * Gets addedDate
     *
     * @return string|null
     */
    public function getAddedDate(): ?string
    {
        return $this->container['addedDate'];
    }

    /**
     * Sets addedDate
     *
     * @param string|null $addedDate Added date.
     *
     * @return $this
     */
    public function setAddedDate(?string $addedDate): static
    {
        if (is_null($addedDate)) {
            array_push($this->openAPINullablesSetToNull, 'addedDate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('addedDate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['addedDate'] = $addedDate;

        return $this;
    }

    /**
     * Gets addedBy
     *
     * @return \Equisoft\SDK\EquisoftConnect\Model\MovementUser|null
     */
    public function getAddedBy(): ?\Equisoft\SDK\EquisoftConnect\Model\MovementUser
    {
        return $this->container['addedBy'];
    }

    /**
     * Sets addedBy
     *
     * @param \Equisoft\SDK\EquisoftConnect\Model\MovementUser|null $addedBy addedBy
     *
     * @return $this
     */
    public function setAddedBy(?\Equisoft\SDK\EquisoftConnect\Model\MovementUser $addedBy): static
    {
        if (is_null($addedBy)) {
            array_push($this->openAPINullablesSetToNull, 'addedBy');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('addedBy', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['addedBy'] = $addedBy;

        return $this;
    }

    /**
     * Gets cancelledDate
     *
     * @return string|null
     */
    public function getCancelledDate(): ?string
    {
        return $this->container['cancelledDate'];
    }

    /**
     * Sets cancelledDate
     *
     * @param string|null $cancelledDate Cancelled date.
     *
     * @return $this
     */
    public function setCancelledDate(?string $cancelledDate): static
    {
        if (is_null($cancelledDate)) {
            array_push($this->openAPINullablesSetToNull, 'cancelledDate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cancelledDate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cancelledDate'] = $cancelledDate;

        return $this;
    }

    /**
     * Gets cancelledBy
     *
     * @return \Equisoft\SDK\EquisoftConnect\Model\MovementUser|null
     */
    public function getCancelledBy(): ?\Equisoft\SDK\EquisoftConnect\Model\MovementUser
    {
        return $this->container['cancelledBy'];
    }

    /**
     * Sets cancelledBy
     *
     * @param \Equisoft\SDK\EquisoftConnect\Model\MovementUser|null $cancelledBy cancelledBy
     *
     * @return $this
     */
    public function setCancelledBy(?\Equisoft\SDK\EquisoftConnect\Model\MovementUser $cancelledBy): static
    {
        if (is_null($cancelledBy)) {
            array_push($this->openAPINullablesSetToNull, 'cancelledBy');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cancelledBy', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cancelledBy'] = $cancelledBy;

        return $this;
    }

    /**
     * Gets sourceDatabase
     *
     * @return \Equisoft\SDK\EquisoftConnect\Model\MovementDatabase
     */
    public function getSourceDatabase(): \Equisoft\SDK\EquisoftConnect\Model\MovementDatabase
    {
        return $this->container['sourceDatabase'];
    }

    /**
     * Sets sourceDatabase
     *
     * @param \Equisoft\SDK\EquisoftConnect\Model\MovementDatabase $sourceDatabase sourceDatabase
     *
     * @return $this
     */
    public function setSourceDatabase(\Equisoft\SDK\EquisoftConnect\Model\MovementDatabase $sourceDatabase): static
    {
        if (is_null($sourceDatabase)) {
            throw new InvalidArgumentException('non-nullable sourceDatabase cannot be null');
        }
        $this->container['sourceDatabase'] = $sourceDatabase;

        return $this;
    }

    /**
     * Gets destinationDatabase
     *
     * @return \Equisoft\SDK\EquisoftConnect\Model\MovementDatabase
     */
    public function getDestinationDatabase(): \Equisoft\SDK\EquisoftConnect\Model\MovementDatabase
    {
        return $this->container['destinationDatabase'];
    }

    /**
     * Sets destinationDatabase
     *
     * @param \Equisoft\SDK\EquisoftConnect\Model\MovementDatabase $destinationDatabase destinationDatabase
     *
     * @return $this
     */
    public function setDestinationDatabase(\Equisoft\SDK\EquisoftConnect\Model\MovementDatabase $destinationDatabase): static
    {
        if (is_null($destinationDatabase)) {
            throw new InvalidArgumentException('non-nullable destinationDatabase cannot be null');
        }
        $this->container['destinationDatabase'] = $destinationDatabase;

        return $this;
    }

    /**
     * Gets users
     *
     * @return \Equisoft\SDK\EquisoftConnect\Model\MovementUser[]
     */
    public function getUsers(): array
    {
        return $this->container['users'];
    }

    /**
     * Sets users
     *
     * @param \Equisoft\SDK\EquisoftConnect\Model\MovementUser[] $users List of users.
     *
     * @return $this
     */
    public function setUsers(array $users): static
    {
        if (is_null($users)) {
            throw new InvalidArgumentException('non-nullable users cannot be null');
        }
        $this->container['users'] = $users;

        return $this;
    }

    /**
     * Gets userTuples
     *
     * @return \Equisoft\SDK\EquisoftConnect\Model\MovementUserTuple[]
     */
    public function getUserTuples(): array
    {
        return $this->container['userTuples'];
    }

    /**
     * Sets userTuples
     *
     * @param \Equisoft\SDK\EquisoftConnect\Model\MovementUserTuple[] $userTuples List of user tuples.
     *
     * @return $this
     */
    public function setUserTuples(array $userTuples): static
    {
        if (is_null($userTuples)) {
            throw new InvalidArgumentException('non-nullable userTuples cannot be null');
        }
        $this->container['userTuples'] = $userTuples;

        return $this;
    }

    /**
     * Gets sourceUser
     *
     * @return \Equisoft\SDK\EquisoftConnect\Model\MovementUser
     */
    public function getSourceUser(): \Equisoft\SDK\EquisoftConnect\Model\MovementUser
    {
        return $this->container['sourceUser'];
    }

    /**
     * Sets sourceUser
     *
     * @param \Equisoft\SDK\EquisoftConnect\Model\MovementUser $sourceUser sourceUser
     *
     * @return $this
     */
    public function setSourceUser(\Equisoft\SDK\EquisoftConnect\Model\MovementUser $sourceUser): static
    {
        if (is_null($sourceUser)) {
            throw new InvalidArgumentException('non-nullable sourceUser cannot be null');
        }
        $this->container['sourceUser'] = $sourceUser;

        return $this;
    }

    /**
     * Gets sourceDistributionList
     *
     * @return \Equisoft\SDK\EquisoftConnect\Model\MovementDistributionList|null
     */
    public function getSourceDistributionList(): ?\Equisoft\SDK\EquisoftConnect\Model\MovementDistributionList
    {
        return $this->container['sourceDistributionList'];
    }

    /**
     * Sets sourceDistributionList
     *
     * @param \Equisoft\SDK\EquisoftConnect\Model\MovementDistributionList|null $sourceDistributionList sourceDistributionList
     *
     * @return $this
     */
    public function setSourceDistributionList(?\Equisoft\SDK\EquisoftConnect\Model\MovementDistributionList $sourceDistributionList): static
    {
        if (is_null($sourceDistributionList)) {
            throw new InvalidArgumentException('non-nullable sourceDistributionList cannot be null');
        }
        $this->container['sourceDistributionList'] = $sourceDistributionList;

        return $this;
    }

    /**
     * Gets destinationUser
     *
     * @return \Equisoft\SDK\EquisoftConnect\Model\MovementUser
     */
    public function getDestinationUser(): \Equisoft\SDK\EquisoftConnect\Model\MovementUser
    {
        return $this->container['destinationUser'];
    }

    /**
     * Sets destinationUser
     *
     * @param \Equisoft\SDK\EquisoftConnect\Model\MovementUser $destinationUser destinationUser
     *
     * @return $this
     */
    public function setDestinationUser(\Equisoft\SDK\EquisoftConnect\Model\MovementUser $destinationUser): static
    {
        if (is_null($destinationUser)) {
            throw new InvalidArgumentException('non-nullable destinationUser cannot be null');
        }
        $this->container['destinationUser'] = $destinationUser;

        return $this;
    }

    /**
     * Gets transferOption
     *
     * @return \Equisoft\SDK\EquisoftConnect\Model\MovementTransferOption
     */
    public function getTransferOption(): \Equisoft\SDK\EquisoftConnect\Model\MovementTransferOption
    {
        return $this->container['transferOption'];
    }

    /**
     * Sets transferOption
     *
     * @param \Equisoft\SDK\EquisoftConnect\Model\MovementTransferOption $transferOption transferOption
     *
     * @return $this
     */
    public function setTransferOption(\Equisoft\SDK\EquisoftConnect\Model\MovementTransferOption $transferOption): static
    {
        if (is_null($transferOption)) {
            throw new InvalidArgumentException('non-nullable transferOption cannot be null');
        }
        $this->container['transferOption'] = $transferOption;

        return $this;
    }

    /**
     * Gets capsil
     *
     * @return bool|null
     */
    public function getCapsil(): ?bool
    {
        return $this->container['capsil'];
    }

    /**
     * Sets capsil
     *
     * @param bool|null $capsil Is Capsil.
     *
     * @return $this
     */
    public function setCapsil(?bool $capsil): static
    {
        if (is_null($capsil)) {
            throw new InvalidArgumentException('non-nullable capsil cannot be null');
        }
        $this->container['capsil'] = $capsil;

        return $this;
    }

    /**
     * Gets univeris
     *
     * @return bool|null
     * @deprecated
     */
    public function getUniveris(): ?bool
    {
        return $this->container['univeris'];
    }

    /**
     * Sets univeris
     *
     * @param bool|null $univeris Is Univeris. Deprecated: Univeris is not supported anymore and will be removed from future versions).
     *
     * @return $this
     * @deprecated
     */
    public function setUniveris(?bool $univeris): static
    {
        if (is_null($univeris)) {
            throw new InvalidArgumentException('non-nullable univeris cannot be null');
        }
        $this->container['univeris'] = $univeris;

        return $this;
    }

    /**
     * Gets dataphile
     *
     * @return bool|null
     */
    public function getDataphile(): ?bool
    {
        return $this->container['dataphile'];
    }

    /**
     * Sets dataphile
     *
     * @param bool|null $dataphile Is Dataphile.
     *
     * @return $this
     */
    public function setDataphile(?bool $dataphile): static
    {
        if (is_null($dataphile)) {
            throw new InvalidArgumentException('non-nullable dataphile cannot be null');
        }
        $this->container['dataphile'] = $dataphile;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


