<?php
/**
 * LegacyContactContactListItem
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Equisoft\SDK\EquisoftConnect\Model;

use \ArrayAccess;
use \Equisoft\SDK\EquisoftConnect\ObjectSerializer;

/**
 * LegacyContactContactListItem Class Doc Comment
 *
 * @category Class
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LegacyContactContactListItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'legacy.contact.ContactListItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'uuid' => 'string',
        'typeContact' => 'string',
        'indOrg' => 'string',
        'displayName' => 'string',
        'firstName' => 'string',
        'nickname' => 'string',
        'middleName' => 'string',
        'lastName' => 'string',
        'corporationName' => 'string',
        'corporationNameLine2' => 'string',
        'rank' => 'string',
        'facebookLink' => 'string',
        'twitterLink' => 'string',
        'linkedinLink' => 'string',
        'avatar' => 'int',
        'mainEmail' => 'string',
        'mainPhone' => 'string',
        'addressLine1' => 'string',
        'addressLine2' => 'string',
        'city' => 'string',
        'stateProvince' => 'string',
        'country' => 'string',
        'postalCode' => 'string',
        'civicNumber' => 'string',
        'road' => 'string',
        'extType' => 'string',
        'extNumber' => 'string',
        'birthdate' => 'string',
        'gender' => 'string',
        'dateModified' => 'string',
        'dateCreated' => 'string',
        'spouseId' => 'int',
        'spouseDisplayName' => 'string',
        'spouseFirstName' => 'string',
        'spouseLastName' => 'string',
        'spouseBirthdate' => 'string',
        'spouseGender' => 'string',
        'class' => 'string',
        'classIds' => '\Equisoft\SDK\EquisoftConnect\Model\LegacyInt[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'uuid' => null,
        'typeContact' => null,
        'indOrg' => null,
        'displayName' => null,
        'firstName' => null,
        'nickname' => null,
        'middleName' => null,
        'lastName' => null,
        'corporationName' => null,
        'corporationNameLine2' => null,
        'rank' => null,
        'facebookLink' => null,
        'twitterLink' => null,
        'linkedinLink' => null,
        'avatar' => null,
        'mainEmail' => null,
        'mainPhone' => null,
        'addressLine1' => null,
        'addressLine2' => null,
        'city' => null,
        'stateProvince' => null,
        'country' => null,
        'postalCode' => null,
        'civicNumber' => null,
        'road' => null,
        'extType' => null,
        'extNumber' => null,
        'birthdate' => null,
        'gender' => null,
        'dateModified' => null,
        'dateCreated' => null,
        'spouseId' => null,
        'spouseDisplayName' => null,
        'spouseFirstName' => null,
        'spouseLastName' => null,
        'spouseBirthdate' => null,
        'spouseGender' => null,
        'class' => null,
        'classIds' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'uuid' => 'uuid',
        'typeContact' => 'typeContact',
        'indOrg' => 'indOrg',
        'displayName' => 'displayName',
        'firstName' => 'firstName',
        'nickname' => 'nickname',
        'middleName' => 'middleName',
        'lastName' => 'lastName',
        'corporationName' => 'corporationName',
        'corporationNameLine2' => 'corporationNameLine2',
        'rank' => 'rank',
        'facebookLink' => 'facebookLink',
        'twitterLink' => 'twitterLink',
        'linkedinLink' => 'linkedinLink',
        'avatar' => 'avatar',
        'mainEmail' => 'mainEmail',
        'mainPhone' => 'mainPhone',
        'addressLine1' => 'addressLine1',
        'addressLine2' => 'addressLine2',
        'city' => 'city',
        'stateProvince' => 'stateProvince',
        'country' => 'country',
        'postalCode' => 'postalCode',
        'civicNumber' => 'civicNumber',
        'road' => 'road',
        'extType' => 'extType',
        'extNumber' => 'extNumber',
        'birthdate' => 'birthdate',
        'gender' => 'gender',
        'dateModified' => 'date_modified',
        'dateCreated' => 'date_created',
        'spouseId' => 'spouseId',
        'spouseDisplayName' => 'spouseDisplayName',
        'spouseFirstName' => 'spouseFirstName',
        'spouseLastName' => 'spouseLastName',
        'spouseBirthdate' => 'spouseBirthdate',
        'spouseGender' => 'spouseGender',
        'class' => 'class',
        'classIds' => 'classIds'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'uuid' => 'setUuid',
        'typeContact' => 'setTypeContact',
        'indOrg' => 'setIndOrg',
        'displayName' => 'setDisplayName',
        'firstName' => 'setFirstName',
        'nickname' => 'setNickname',
        'middleName' => 'setMiddleName',
        'lastName' => 'setLastName',
        'corporationName' => 'setCorporationName',
        'corporationNameLine2' => 'setCorporationNameLine2',
        'rank' => 'setRank',
        'facebookLink' => 'setFacebookLink',
        'twitterLink' => 'setTwitterLink',
        'linkedinLink' => 'setLinkedinLink',
        'avatar' => 'setAvatar',
        'mainEmail' => 'setMainEmail',
        'mainPhone' => 'setMainPhone',
        'addressLine1' => 'setAddressLine1',
        'addressLine2' => 'setAddressLine2',
        'city' => 'setCity',
        'stateProvince' => 'setStateProvince',
        'country' => 'setCountry',
        'postalCode' => 'setPostalCode',
        'civicNumber' => 'setCivicNumber',
        'road' => 'setRoad',
        'extType' => 'setExtType',
        'extNumber' => 'setExtNumber',
        'birthdate' => 'setBirthdate',
        'gender' => 'setGender',
        'dateModified' => 'setDateModified',
        'dateCreated' => 'setDateCreated',
        'spouseId' => 'setSpouseId',
        'spouseDisplayName' => 'setSpouseDisplayName',
        'spouseFirstName' => 'setSpouseFirstName',
        'spouseLastName' => 'setSpouseLastName',
        'spouseBirthdate' => 'setSpouseBirthdate',
        'spouseGender' => 'setSpouseGender',
        'class' => 'setClass',
        'classIds' => 'setClassIds'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'uuid' => 'getUuid',
        'typeContact' => 'getTypeContact',
        'indOrg' => 'getIndOrg',
        'displayName' => 'getDisplayName',
        'firstName' => 'getFirstName',
        'nickname' => 'getNickname',
        'middleName' => 'getMiddleName',
        'lastName' => 'getLastName',
        'corporationName' => 'getCorporationName',
        'corporationNameLine2' => 'getCorporationNameLine2',
        'rank' => 'getRank',
        'facebookLink' => 'getFacebookLink',
        'twitterLink' => 'getTwitterLink',
        'linkedinLink' => 'getLinkedinLink',
        'avatar' => 'getAvatar',
        'mainEmail' => 'getMainEmail',
        'mainPhone' => 'getMainPhone',
        'addressLine1' => 'getAddressLine1',
        'addressLine2' => 'getAddressLine2',
        'city' => 'getCity',
        'stateProvince' => 'getStateProvince',
        'country' => 'getCountry',
        'postalCode' => 'getPostalCode',
        'civicNumber' => 'getCivicNumber',
        'road' => 'getRoad',
        'extType' => 'getExtType',
        'extNumber' => 'getExtNumber',
        'birthdate' => 'getBirthdate',
        'gender' => 'getGender',
        'dateModified' => 'getDateModified',
        'dateCreated' => 'getDateCreated',
        'spouseId' => 'getSpouseId',
        'spouseDisplayName' => 'getSpouseDisplayName',
        'spouseFirstName' => 'getSpouseFirstName',
        'spouseLastName' => 'getSpouseLastName',
        'spouseBirthdate' => 'getSpouseBirthdate',
        'spouseGender' => 'getSpouseGender',
        'class' => 'getClass',
        'classIds' => 'getClassIds'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['uuid'] = $data['uuid'] ?? null;
        $this->container['typeContact'] = $data['typeContact'] ?? null;
        $this->container['indOrg'] = $data['indOrg'] ?? null;
        $this->container['displayName'] = $data['displayName'] ?? null;
        $this->container['firstName'] = $data['firstName'] ?? null;
        $this->container['nickname'] = $data['nickname'] ?? null;
        $this->container['middleName'] = $data['middleName'] ?? null;
        $this->container['lastName'] = $data['lastName'] ?? null;
        $this->container['corporationName'] = $data['corporationName'] ?? null;
        $this->container['corporationNameLine2'] = $data['corporationNameLine2'] ?? null;
        $this->container['rank'] = $data['rank'] ?? null;
        $this->container['facebookLink'] = $data['facebookLink'] ?? null;
        $this->container['twitterLink'] = $data['twitterLink'] ?? null;
        $this->container['linkedinLink'] = $data['linkedinLink'] ?? null;
        $this->container['avatar'] = $data['avatar'] ?? null;
        $this->container['mainEmail'] = $data['mainEmail'] ?? null;
        $this->container['mainPhone'] = $data['mainPhone'] ?? null;
        $this->container['addressLine1'] = $data['addressLine1'] ?? null;
        $this->container['addressLine2'] = $data['addressLine2'] ?? null;
        $this->container['city'] = $data['city'] ?? null;
        $this->container['stateProvince'] = $data['stateProvince'] ?? null;
        $this->container['country'] = $data['country'] ?? null;
        $this->container['postalCode'] = $data['postalCode'] ?? null;
        $this->container['civicNumber'] = $data['civicNumber'] ?? null;
        $this->container['road'] = $data['road'] ?? null;
        $this->container['extType'] = $data['extType'] ?? null;
        $this->container['extNumber'] = $data['extNumber'] ?? null;
        $this->container['birthdate'] = $data['birthdate'] ?? null;
        $this->container['gender'] = $data['gender'] ?? null;
        $this->container['dateModified'] = $data['dateModified'] ?? null;
        $this->container['dateCreated'] = $data['dateCreated'] ?? null;
        $this->container['spouseId'] = $data['spouseId'] ?? null;
        $this->container['spouseDisplayName'] = $data['spouseDisplayName'] ?? null;
        $this->container['spouseFirstName'] = $data['spouseFirstName'] ?? null;
        $this->container['spouseLastName'] = $data['spouseLastName'] ?? null;
        $this->container['spouseBirthdate'] = $data['spouseBirthdate'] ?? null;
        $this->container['spouseGender'] = $data['spouseGender'] ?? null;
        $this->container['class'] = $data['class'] ?? null;
        $this->container['classIds'] = $data['classIds'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id Id of the contact.
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets uuid
     *
     * @return string|null
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param string|null $uuid Contact UUID.
     *
     * @return self
     */
    public function setUuid($uuid)
    {
        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets typeContact
     *
     * @return string|null
     */
    public function getTypeContact()
    {
        return $this->container['typeContact'];
    }

    /**
     * Sets typeContact
     *
     * @param string|null $typeContact Type of the contact.
     *
     * @return self
     */
    public function setTypeContact($typeContact)
    {
        $this->container['typeContact'] = $typeContact;

        return $this;
    }

    /**
     * Gets indOrg
     *
     * @return string|null
     */
    public function getIndOrg()
    {
        return $this->container['indOrg'];
    }

    /**
     * Sets indOrg
     *
     * @param string|null $indOrg Type INDIVIDUAL OR ORGANIZATION.
     *
     * @return self
     */
    public function setIndOrg($indOrg)
    {
        $this->container['indOrg'] = $indOrg;

        return $this;
    }

    /**
     * Gets displayName
     *
     * @return string|null
     */
    public function getDisplayName()
    {
        return $this->container['displayName'];
    }

    /**
     * Sets displayName
     *
     * @param string|null $displayName Display name of the contact.
     *
     * @return self
     */
    public function setDisplayName($displayName)
    {
        $this->container['displayName'] = $displayName;

        return $this;
    }

    /**
     * Gets firstName
     *
     * @return string|null
     */
    public function getFirstName()
    {
        return $this->container['firstName'];
    }

    /**
     * Sets firstName
     *
     * @param string|null $firstName First name of the contact.
     *
     * @return self
     */
    public function setFirstName($firstName)
    {
        $this->container['firstName'] = $firstName;

        return $this;
    }

    /**
     * Gets nickname
     *
     * @return string|null
     */
    public function getNickname()
    {
        return $this->container['nickname'];
    }

    /**
     * Sets nickname
     *
     * @param string|null $nickname Nickname of the contact.
     *
     * @return self
     */
    public function setNickname($nickname)
    {
        $this->container['nickname'] = $nickname;

        return $this;
    }

    /**
     * Gets middleName
     *
     * @return string|null
     */
    public function getMiddleName()
    {
        return $this->container['middleName'];
    }

    /**
     * Sets middleName
     *
     * @param string|null $middleName Middle name of the contact.
     *
     * @return self
     */
    public function setMiddleName($middleName)
    {
        $this->container['middleName'] = $middleName;

        return $this;
    }

    /**
     * Gets lastName
     *
     * @return string|null
     */
    public function getLastName()
    {
        return $this->container['lastName'];
    }

    /**
     * Sets lastName
     *
     * @param string|null $lastName Last name of the contact.
     *
     * @return self
     */
    public function setLastName($lastName)
    {
        $this->container['lastName'] = $lastName;

        return $this;
    }

    /**
     * Gets corporationName
     *
     * @return string|null
     */
    public function getCorporationName()
    {
        return $this->container['corporationName'];
    }

    /**
     * Sets corporationName
     *
     * @param string|null $corporationName First line of corporation name (Organization).
     *
     * @return self
     */
    public function setCorporationName($corporationName)
    {
        $this->container['corporationName'] = $corporationName;

        return $this;
    }

    /**
     * Gets corporationNameLine2
     *
     * @return string|null
     */
    public function getCorporationNameLine2()
    {
        return $this->container['corporationNameLine2'];
    }

    /**
     * Sets corporationNameLine2
     *
     * @param string|null $corporationNameLine2 Second line of corporation name (Organization).
     *
     * @return self
     */
    public function setCorporationNameLine2($corporationNameLine2)
    {
        $this->container['corporationNameLine2'] = $corporationNameLine2;

        return $this;
    }

    /**
     * Gets rank
     *
     * @return string|null
     */
    public function getRank()
    {
        return $this->container['rank'];
    }

    /**
     * Sets rank
     *
     * @param string|null $rank Rank of the contact. (Industrial Alliance only).
     *
     * @return self
     */
    public function setRank($rank)
    {
        $this->container['rank'] = $rank;

        return $this;
    }

    /**
     * Gets facebookLink
     *
     * @return string|null
     */
    public function getFacebookLink()
    {
        return $this->container['facebookLink'];
    }

    /**
     * Sets facebookLink
     *
     * @param string|null $facebookLink Facebook link.
     *
     * @return self
     */
    public function setFacebookLink($facebookLink)
    {
        $this->container['facebookLink'] = $facebookLink;

        return $this;
    }

    /**
     * Gets twitterLink
     *
     * @return string|null
     */
    public function getTwitterLink()
    {
        return $this->container['twitterLink'];
    }

    /**
     * Sets twitterLink
     *
     * @param string|null $twitterLink Twitter link.
     *
     * @return self
     */
    public function setTwitterLink($twitterLink)
    {
        $this->container['twitterLink'] = $twitterLink;

        return $this;
    }

    /**
     * Gets linkedinLink
     *
     * @return string|null
     */
    public function getLinkedinLink()
    {
        return $this->container['linkedinLink'];
    }

    /**
     * Sets linkedinLink
     *
     * @param string|null $linkedinLink LinkedIn link.
     *
     * @return self
     */
    public function setLinkedinLink($linkedinLink)
    {
        $this->container['linkedinLink'] = $linkedinLink;

        return $this;
    }

    /**
     * Gets avatar
     *
     * @return int|null
     */
    public function getAvatar()
    {
        return $this->container['avatar'];
    }

    /**
     * Sets avatar
     *
     * @param int|null $avatar Avatar.
     *
     * @return self
     */
    public function setAvatar($avatar)
    {
        $this->container['avatar'] = $avatar;

        return $this;
    }

    /**
     * Gets mainEmail
     *
     * @return string|null
     */
    public function getMainEmail()
    {
        return $this->container['mainEmail'];
    }

    /**
     * Sets mainEmail
     *
     * @param string|null $mainEmail Main email of the contact.
     *
     * @return self
     */
    public function setMainEmail($mainEmail)
    {
        $this->container['mainEmail'] = $mainEmail;

        return $this;
    }

    /**
     * Gets mainPhone
     *
     * @return string|null
     */
    public function getMainPhone()
    {
        return $this->container['mainPhone'];
    }

    /**
     * Sets mainPhone
     *
     * @param string|null $mainPhone Main phone number.
     *
     * @return self
     */
    public function setMainPhone($mainPhone)
    {
        $this->container['mainPhone'] = $mainPhone;

        return $this;
    }

    /**
     * Gets addressLine1
     *
     * @return string|null
     */
    public function getAddressLine1()
    {
        return $this->container['addressLine1'];
    }

    /**
     * Sets addressLine1
     *
     * @param string|null $addressLine1 First line of address of the contact.
     *
     * @return self
     */
    public function setAddressLine1($addressLine1)
    {
        $this->container['addressLine1'] = $addressLine1;

        return $this;
    }

    /**
     * Gets addressLine2
     *
     * @return string|null
     */
    public function getAddressLine2()
    {
        return $this->container['addressLine2'];
    }

    /**
     * Sets addressLine2
     *
     * @param string|null $addressLine2 Second line of address of the contact.
     *
     * @return self
     */
    public function setAddressLine2($addressLine2)
    {
        $this->container['addressLine2'] = $addressLine2;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string|null
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string|null $city City of the contact.
     *
     * @return self
     */
    public function setCity($city)
    {
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets stateProvince
     *
     * @return string|null
     */
    public function getStateProvince()
    {
        return $this->container['stateProvince'];
    }

    /**
     * Sets stateProvince
     *
     * @param string|null $stateProvince State or province of the contact.
     *
     * @return self
     */
    public function setStateProvince($stateProvince)
    {
        $this->container['stateProvince'] = $stateProvince;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country Country of the contact.
     *
     * @return self
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets postalCode
     *
     * @return string|null
     */
    public function getPostalCode()
    {
        return $this->container['postalCode'];
    }

    /**
     * Sets postalCode
     *
     * @param string|null $postalCode PostalCode of the contact.
     *
     * @return self
     */
    public function setPostalCode($postalCode)
    {
        $this->container['postalCode'] = $postalCode;

        return $this;
    }

    /**
     * Gets civicNumber
     *
     * @return string|null
     */
    public function getCivicNumber()
    {
        return $this->container['civicNumber'];
    }

    /**
     * Sets civicNumber
     *
     * @param string|null $civicNumber Industrielle Alliance Only.
     *
     * @return self
     */
    public function setCivicNumber($civicNumber)
    {
        $this->container['civicNumber'] = $civicNumber;

        return $this;
    }

    /**
     * Gets road
     *
     * @return string|null
     */
    public function getRoad()
    {
        return $this->container['road'];
    }

    /**
     * Sets road
     *
     * @param string|null $road Industrielle Alliance Only.
     *
     * @return self
     */
    public function setRoad($road)
    {
        $this->container['road'] = $road;

        return $this;
    }

    /**
     * Gets extType
     *
     * @return string|null
     */
    public function getExtType()
    {
        return $this->container['extType'];
    }

    /**
     * Sets extType
     *
     * @param string|null $extType Industrielle Alliance Only.
     *
     * @return self
     */
    public function setExtType($extType)
    {
        $this->container['extType'] = $extType;

        return $this;
    }

    /**
     * Gets extNumber
     *
     * @return string|null
     */
    public function getExtNumber()
    {
        return $this->container['extNumber'];
    }

    /**
     * Sets extNumber
     *
     * @param string|null $extNumber Industrielle Alliance Only.
     *
     * @return self
     */
    public function setExtNumber($extNumber)
    {
        $this->container['extNumber'] = $extNumber;

        return $this;
    }

    /**
     * Gets birthdate
     *
     * @return string|null
     */
    public function getBirthdate()
    {
        return $this->container['birthdate'];
    }

    /**
     * Sets birthdate
     *
     * @param string|null $birthdate Birthdate.
     *
     * @return self
     */
    public function setBirthdate($birthdate)
    {
        $this->container['birthdate'] = $birthdate;

        return $this;
    }

    /**
     * Gets gender
     *
     * @return string|null
     */
    public function getGender()
    {
        return $this->container['gender'];
    }

    /**
     * Sets gender
     *
     * @param string|null $gender Gender of the contact. Either MALE or FEMALE.
     *
     * @return self
     */
    public function setGender($gender)
    {
        $this->container['gender'] = $gender;

        return $this;
    }

    /**
     * Gets dateModified
     *
     * @return string|null
     */
    public function getDateModified()
    {
        return $this->container['dateModified'];
    }

    /**
     * Sets dateModified
     *
     * @param string|null $dateModified Date modified.
     *
     * @return self
     */
    public function setDateModified($dateModified)
    {
        $this->container['dateModified'] = $dateModified;

        return $this;
    }

    /**
     * Gets dateCreated
     *
     * @return string|null
     */
    public function getDateCreated()
    {
        return $this->container['dateCreated'];
    }

    /**
     * Sets dateCreated
     *
     * @param string|null $dateCreated Date created.
     *
     * @return self
     */
    public function setDateCreated($dateCreated)
    {
        $this->container['dateCreated'] = $dateCreated;

        return $this;
    }

    /**
     * Gets spouseId
     *
     * @return int|null
     */
    public function getSpouseId()
    {
        return $this->container['spouseId'];
    }

    /**
     * Sets spouseId
     *
     * @param int|null $spouseId Id of the spouse contact.
     *
     * @return self
     */
    public function setSpouseId($spouseId)
    {
        $this->container['spouseId'] = $spouseId;

        return $this;
    }

    /**
     * Gets spouseDisplayName
     *
     * @return string|null
     */
    public function getSpouseDisplayName()
    {
        return $this->container['spouseDisplayName'];
    }

    /**
     * Sets spouseDisplayName
     *
     * @param string|null $spouseDisplayName Display name  of the spouse contact.
     *
     * @return self
     */
    public function setSpouseDisplayName($spouseDisplayName)
    {
        $this->container['spouseDisplayName'] = $spouseDisplayName;

        return $this;
    }

    /**
     * Gets spouseFirstName
     *
     * @return string|null
     */
    public function getSpouseFirstName()
    {
        return $this->container['spouseFirstName'];
    }

    /**
     * Sets spouseFirstName
     *
     * @param string|null $spouseFirstName First name of the spouse contact.
     *
     * @return self
     */
    public function setSpouseFirstName($spouseFirstName)
    {
        $this->container['spouseFirstName'] = $spouseFirstName;

        return $this;
    }

    /**
     * Gets spouseLastName
     *
     * @return string|null
     */
    public function getSpouseLastName()
    {
        return $this->container['spouseLastName'];
    }

    /**
     * Sets spouseLastName
     *
     * @param string|null $spouseLastName Last name of the spouse contact.
     *
     * @return self
     */
    public function setSpouseLastName($spouseLastName)
    {
        $this->container['spouseLastName'] = $spouseLastName;

        return $this;
    }

    /**
     * Gets spouseBirthdate
     *
     * @return string|null
     */
    public function getSpouseBirthdate()
    {
        return $this->container['spouseBirthdate'];
    }

    /**
     * Sets spouseBirthdate
     *
     * @param string|null $spouseBirthdate Birthdate of the spouse contact.
     *
     * @return self
     */
    public function setSpouseBirthdate($spouseBirthdate)
    {
        $this->container['spouseBirthdate'] = $spouseBirthdate;

        return $this;
    }

    /**
     * Gets spouseGender
     *
     * @return string|null
     */
    public function getSpouseGender()
    {
        return $this->container['spouseGender'];
    }

    /**
     * Sets spouseGender
     *
     * @param string|null $spouseGender Gender of the spouse. Either MALE or FEMALE.
     *
     * @return self
     */
    public function setSpouseGender($spouseGender)
    {
        $this->container['spouseGender'] = $spouseGender;

        return $this;
    }

    /**
     * Gets class
     *
     * @return string|null
     */
    public function getClass()
    {
        return $this->container['class'];
    }

    /**
     * Sets class
     *
     * @param string|null $class Class (separated by ;).
     *
     * @return self
     */
    public function setClass($class)
    {
        $this->container['class'] = $class;

        return $this;
    }

    /**
     * Gets classIds
     *
     * @return \Equisoft\SDK\EquisoftConnect\Model\LegacyInt[]|null
     */
    public function getClassIds()
    {
        return $this->container['classIds'];
    }

    /**
     * Sets classIds
     *
     * @param \Equisoft\SDK\EquisoftConnect\Model\LegacyInt[]|null $classIds Class ids.
     *
     * @return self
     */
    public function setClassIds($classIds)
    {
        $this->container['classIds'] = $classIds;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


