<?php
/**
 * MovementMovementStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Equisoft\SDK\EquisoftConnect\Model;
use \Equisoft\SDK\EquisoftConnect\ObjectSerializer;

/**
 * MovementMovementStatus Class Doc Comment
 *
 * @category Class
 * @description Movement status.
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MovementMovementStatus
{
    /**
     * Possible values of this enum
     */
    public const TODO = 'TODO';

    public const CANCELLED = 'CANCELLED';

    public const IGNORED = 'IGNORED';

    public const FAILURE = 'FAILURE';

    public const SUCCESS = 'SUCCESS';

    public const UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TODO,
            self::CANCELLED,
            self::IGNORED,
            self::FAILURE,
            self::SUCCESS,
            self::UNKNOWN_DEFAULT_OPEN_API
        ];
    }
}


