<?php
/**
 * TasksCreateTaskPayload
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0-equisoft-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Equisoft\SDK\EquisoftConnect\Model;

use \ArrayAccess;
use \Equisoft\SDK\EquisoftConnect\ObjectSerializer;

/**
 * TasksCreateTaskPayload Class Doc Comment
 *
 * @category Class
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TasksCreateTaskPayload implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'tasks.CreateTaskPayload';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'subject' => 'string',
        'dueDate' => 'string',
        'initialDate' => 'string',
        'completedDate' => 'string',
        'description' => 'string',
        'internalNotes' => 'string',
        'categoryId' => 'int',
        'subCategoryId' => 'int',
        'priority' => 'int',
        'visibility' => 'string',
        'contactIds' => 'int[]',
        'ownerIds' => 'int[]',
        'isCompleted' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'subject' => null,
        'dueDate' => null,
        'initialDate' => null,
        'completedDate' => null,
        'description' => null,
        'internalNotes' => null,
        'categoryId' => null,
        'subCategoryId' => null,
        'priority' => null,
        'visibility' => null,
        'contactIds' => null,
        'ownerIds' => null,
        'isCompleted' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'subject' => false,
		'dueDate' => false,
		'initialDate' => false,
		'completedDate' => false,
		'description' => false,
		'internalNotes' => false,
		'categoryId' => false,
		'subCategoryId' => false,
		'priority' => false,
		'visibility' => false,
		'contactIds' => false,
		'ownerIds' => false,
		'isCompleted' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'subject' => 'subject',
        'dueDate' => 'dueDate',
        'initialDate' => 'initialDate',
        'completedDate' => 'completedDate',
        'description' => 'description',
        'internalNotes' => 'internalNotes',
        'categoryId' => 'categoryId',
        'subCategoryId' => 'subCategoryId',
        'priority' => 'priority',
        'visibility' => 'visibility',
        'contactIds' => 'contactIds',
        'ownerIds' => 'ownerIds',
        'isCompleted' => 'isCompleted'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'subject' => 'setSubject',
        'dueDate' => 'setDueDate',
        'initialDate' => 'setInitialDate',
        'completedDate' => 'setCompletedDate',
        'description' => 'setDescription',
        'internalNotes' => 'setInternalNotes',
        'categoryId' => 'setCategoryId',
        'subCategoryId' => 'setSubCategoryId',
        'priority' => 'setPriority',
        'visibility' => 'setVisibility',
        'contactIds' => 'setContactIds',
        'ownerIds' => 'setOwnerIds',
        'isCompleted' => 'setIsCompleted'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'subject' => 'getSubject',
        'dueDate' => 'getDueDate',
        'initialDate' => 'getInitialDate',
        'completedDate' => 'getCompletedDate',
        'description' => 'getDescription',
        'internalNotes' => 'getInternalNotes',
        'categoryId' => 'getCategoryId',
        'subCategoryId' => 'getSubCategoryId',
        'priority' => 'getPriority',
        'visibility' => 'getVisibility',
        'contactIds' => 'getContactIds',
        'ownerIds' => 'getOwnerIds',
        'isCompleted' => 'getIsCompleted'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('subject', $data ?? [], null);
        $this->setIfExists('dueDate', $data ?? [], null);
        $this->setIfExists('initialDate', $data ?? [], null);
        $this->setIfExists('completedDate', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('internalNotes', $data ?? [], null);
        $this->setIfExists('categoryId', $data ?? [], null);
        $this->setIfExists('subCategoryId', $data ?? [], null);
        $this->setIfExists('priority', $data ?? [], null);
        $this->setIfExists('visibility', $data ?? [], null);
        $this->setIfExists('contactIds', $data ?? [], null);
        $this->setIfExists('ownerIds', $data ?? [], null);
        $this->setIfExists('isCompleted', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['subject'] === null) {
            $invalidProperties[] = "'subject' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets subject
     *
     * @return string
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string $subject Subject/Title of the Event.
     *
     * @return self
     */
    public function setSubject($subject)
    {
        if (is_null($subject)) {
            throw new \InvalidArgumentException('non-nullable subject cannot be null');
        }
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets dueDate
     *
     * @return string|null
     */
    public function getDueDate()
    {
        return $this->container['dueDate'];
    }

    /**
     * Sets dueDate
     *
     * @param string|null $dueDate Date the task is expected to be done. As defined by full-date - RFC3339.
     *
     * @return self
     */
    public function setDueDate($dueDate)
    {
        if (is_null($dueDate)) {
            throw new \InvalidArgumentException('non-nullable dueDate cannot be null');
        }
        $this->container['dueDate'] = $dueDate;

        return $this;
    }

    /**
     * Gets initialDate
     *
     * @return string|null
     */
    public function getInitialDate()
    {
        return $this->container['initialDate'];
    }

    /**
     * Sets initialDate
     *
     * @param string|null $initialDate Date the task was initially started. As defined by full-date - RFC3339.
     *
     * @return self
     */
    public function setInitialDate($initialDate)
    {
        if (is_null($initialDate)) {
            throw new \InvalidArgumentException('non-nullable initialDate cannot be null');
        }
        $this->container['initialDate'] = $initialDate;

        return $this;
    }

    /**
     * Gets completedDate
     *
     * @return string|null
     */
    public function getCompletedDate()
    {
        return $this->container['completedDate'];
    }

    /**
     * Sets completedDate
     *
     * @param string|null $completedDate Date the task was completed / done. As defined by full-date - RFC3339.
     *
     * @return self
     */
    public function setCompletedDate($completedDate)
    {
        if (is_null($completedDate)) {
            throw new \InvalidArgumentException('non-nullable completedDate cannot be null');
        }
        $this->container['completedDate'] = $completedDate;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Public description of the Event.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets internalNotes
     *
     * @return string|null
     */
    public function getInternalNotes()
    {
        return $this->container['internalNotes'];
    }

    /**
     * Sets internalNotes
     *
     * @param string|null $internalNotes Internal notes on the Event. Not synced on remote sources.
     *
     * @return self
     */
    public function setInternalNotes($internalNotes)
    {
        if (is_null($internalNotes)) {
            throw new \InvalidArgumentException('non-nullable internalNotes cannot be null');
        }
        $this->container['internalNotes'] = $internalNotes;

        return $this;
    }

    /**
     * Gets categoryId
     *
     * @return int|null
     */
    public function getCategoryId()
    {
        return $this->container['categoryId'];
    }

    /**
     * Sets categoryId
     *
     * @param int|null $categoryId ID of the field value to use as category.
     *
     * @return self
     */
    public function setCategoryId($categoryId)
    {
        if (is_null($categoryId)) {
            throw new \InvalidArgumentException('non-nullable categoryId cannot be null');
        }
        $this->container['categoryId'] = $categoryId;

        return $this;
    }

    /**
     * Gets subCategoryId
     *
     * @return int|null
     */
    public function getSubCategoryId()
    {
        return $this->container['subCategoryId'];
    }

    /**
     * Sets subCategoryId
     *
     * @param int|null $subCategoryId ID of the field value to use as sub-category.
     *
     * @return self
     */
    public function setSubCategoryId($subCategoryId)
    {
        if (is_null($subCategoryId)) {
            throw new \InvalidArgumentException('non-nullable subCategoryId cannot be null');
        }
        $this->container['subCategoryId'] = $subCategoryId;

        return $this;
    }

    /**
     * Gets priority
     *
     * @return int|null
     */
    public function getPriority()
    {
        return $this->container['priority'];
    }

    /**
     * Sets priority
     *
     * @param int|null $priority Importance/Priority of an event or task. 5 is the most important.
     *
     * @return self
     */
    public function setPriority($priority)
    {
        if (is_null($priority)) {
            throw new \InvalidArgumentException('non-nullable priority cannot be null');
        }
        $this->container['priority'] = $priority;

        return $this;
    }

    /**
     * Gets visibility
     *
     * @return string|null
     */
    public function getVisibility()
    {
        return $this->container['visibility'];
    }

    /**
     * Sets visibility
     *
     * @param string|null $visibility Confidentiality level of the Event (private or not). [NORMAL, PRIVATE].
     *
     * @return self
     */
    public function setVisibility($visibility)
    {
        if (is_null($visibility)) {
            throw new \InvalidArgumentException('non-nullable visibility cannot be null');
        }
        $this->container['visibility'] = $visibility;

        return $this;
    }

    /**
     * Gets contactIds
     *
     * @return int[]|null
     */
    public function getContactIds()
    {
        return $this->container['contactIds'];
    }

    /**
     * Sets contactIds
     *
     * @param int[]|null $contactIds Allow to link the task to one or many contacts.
     *
     * @return self
     */
    public function setContactIds($contactIds)
    {
        if (is_null($contactIds)) {
            throw new \InvalidArgumentException('non-nullable contactIds cannot be null');
        }
        $this->container['contactIds'] = $contactIds;

        return $this;
    }

    /**
     * Gets ownerIds
     *
     * @return int[]|null
     */
    public function getOwnerIds()
    {
        return $this->container['ownerIds'];
    }

    /**
     * Sets ownerIds
     *
     * @param int[]|null $ownerIds Ids of the owner users of the task.
     *
     * @return self
     */
    public function setOwnerIds($ownerIds)
    {
        if (is_null($ownerIds)) {
            throw new \InvalidArgumentException('non-nullable ownerIds cannot be null');
        }
        $this->container['ownerIds'] = $ownerIds;

        return $this;
    }

    /**
     * Gets isCompleted
     *
     * @return bool|null
     */
    public function getIsCompleted()
    {
        return $this->container['isCompleted'];
    }

    /**
     * Sets isCompleted
     *
     * @param bool|null $isCompleted Is the task completed.
     *
     * @return self
     */
    public function setIsCompleted($isCompleted)
    {
        if (is_null($isCompleted)) {
            throw new \InvalidArgumentException('non-nullable isCompleted cannot be null');
        }
        $this->container['isCompleted'] = $isCompleted;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


