<?php
/**
 * TasksVisibilityType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Equisoft\SDK\EquisoftConnect\Model;
use \Equisoft\SDK\EquisoftConnect\ObjectSerializer;

/**
 * TasksVisibilityType Class Doc Comment
 *
 * @category Class
 * @description Visibility type.
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TasksVisibilityType
{
    /**
     * Possible values of this enum
     */
    public const NORMAL = 'NORMAL';

    public const _PRIVATE = 'PRIVATE';

    public const UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NORMAL,
            self::_PRIVATE,
            self::UNKNOWN_DEFAULT_OPEN_API
        ];
    }
}


