<?php
/**
 * LegacyDocumentDocumentPayloadItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Equisoft\SDK\EquisoftConnect;

use PHPUnit\Framework\TestCase;

/**
 * LegacyDocumentDocumentPayloadItemTest Class Doc Comment
 *
 * @category    Class
 * @description LegacyDocumentDocumentPayloadItem
 * @package     Equisoft\SDK\EquisoftConnect
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LegacyDocumentDocumentPayloadItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LegacyDocumentDocumentPayloadItem"
     */
    public function testLegacyDocumentDocumentPayloadItem()
    {
    }

    /**
     * Test attribute "files"
     */
    public function testPropertyFiles()
    {
    }

    /**
     * Test attribute "contacts"
     */
    public function testPropertyContacts()
    {
    }

    /**
     * Test attribute "externalKey"
     */
    public function testPropertyExternalKey()
    {
    }

    /**
     * Test attribute "dateStart"
     */
    public function testPropertyDateStart()
    {
    }

    /**
     * Test attribute "dateEnd"
     */
    public function testPropertyDateEnd()
    {
    }

    /**
     * Test attribute "dateSignature"
     */
    public function testPropertyDateSignature()
    {
    }

    /**
     * Test attribute "writtenBy"
     */
    public function testPropertyWrittenBy()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "users"
     */
    public function testPropertyUsers()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "subType"
     */
    public function testPropertySubType()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }
}
