<?php
/**
 * LegacyFinancePolicyCoverageTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0-equisoft4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Equisoft\SDK\EquisoftConnect\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * LegacyFinancePolicyCoverageTest Class Doc Comment
 *
 * @category    Class
 * @description LegacyFinancePolicyCoverage
 * @package     Equisoft\SDK\EquisoftConnect
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LegacyFinancePolicyCoverageTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LegacyFinancePolicyCoverage"
     */
    public function testLegacyFinancePolicyCoverage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "coverageType"
     */
    public function testPropertyCoverageType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "product"
     */
    public function testPropertyProduct()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "productType"
     */
    public function testPropertyProductType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "productTypeSystemName"
     */
    public function testPropertyProductTypeSystemName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "productSubType"
     */
    public function testPropertyProductSubType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "deathCapital"
     */
    public function testPropertyDeathCapital()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "issueDate"
     */
    public function testPropertyIssueDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "annualPremium"
     */
    public function testPropertyAnnualPremium()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "modalPremium"
     */
    public function testPropertyModalPremium()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "annualizedPremium"
     */
    public function testPropertyAnnualizedPremium()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "premiumMode"
     */
    public function testPropertyPremiumMode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "surrenderValue"
     */
    public function testPropertySurrenderValue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "accumulatedFund"
     */
    public function testPropertyAccumulatedFund()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "elimPeriodAcc"
     */
    public function testPropertyElimPeriodAcc()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "elimPeriodSick"
     */
    public function testPropertyElimPeriodSick()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "benefitPeriod"
     */
    public function testPropertyBenefitPeriod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "benefitAmount"
     */
    public function testPropertyBenefitAmount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "beneficiary"
     */
    public function testPropertyBeneficiary()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "insureds"
     */
    public function testPropertyInsureds()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "livesType"
     */
    public function testPropertyLivesType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "coverageOptions"
     */
    public function testPropertyCoverageOptions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "isInsured"
     */
    public function testPropertyIsInsured()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "expiryDate"
     */
    public function testPropertyExpiryDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "accountStatementNotes"
     */
    public function testPropertyAccountStatementNotes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
