<?php
/**
 * TasksTaskTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Equisoft\SDK\EquisoftConnect;

use PHPUnit\Framework\TestCase;

/**
 * TasksTaskTest Class Doc Comment
 *
 * @category    Class
 * @description TasksTask
 * @package     Equisoft\SDK\EquisoftConnect
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TasksTaskTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TasksTask"
     */
    public function testTasksTask()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "isCompleted"
     */
    public function testPropertyIsCompleted()
    {
    }

    /**
     * Test attribute "dueDate"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "initialDate"
     */
    public function testPropertyInitialDate()
    {
    }

    /**
     * Test attribute "completedDate"
     */
    public function testPropertyCompletedDate()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "internalNotes"
     */
    public function testPropertyInternalNotes()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "subCategory"
     */
    public function testPropertySubCategory()
    {
    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {
    }

    /**
     * Test attribute "visibility"
     */
    public function testPropertyVisibility()
    {
    }

    /**
     * Test attribute "creationTime"
     */
    public function testPropertyCreationTime()
    {
    }

    /**
     * Test attribute "updateTime"
     */
    public function testPropertyUpdateTime()
    {
    }

    /**
     * Test attribute "completionTime"
     */
    public function testPropertyCompletionTime()
    {
    }

    /**
     * Test attribute "contactIds"
     */
    public function testPropertyContactIds()
    {
    }

    /**
     * Test attribute "accessRights"
     */
    public function testPropertyAccessRights()
    {
    }
}
