<?php
/**
 * DatabasesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0-equisoft1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Equisoft\SDK\EquisoftConnect\Test\Api;

use \Equisoft\SDK\EquisoftConnect\Configuration;
use \Equisoft\SDK\EquisoftConnect\ApiException;
use \Equisoft\SDK\EquisoftConnect\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DatabasesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Equisoft\SDK\EquisoftConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DatabasesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createChargebeeCustomer
     *
     * Create a ChargeBee customer for the database.
     *
     */
    public function testCreateChargebeeCustomer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDatabase
     *
     * Get a database.
     *
     */
    public function testGetDatabase()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUser
     *
     * Get a database's user.
     *
     */
    public function testGetUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listDatabases
     *
     * List all databases.
     *
     */
    public function testListDatabases()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listUsers
     *
     * List database's users.
     *
     */
    public function testListUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setDatabaseDistributor
     *
     * Set the database's distributor.
     *
     */
    public function testSetDatabaseDistributor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for unsetDatabaseDistributor
     *
     * Unset the database's distributor.
     *
     */
    public function testUnsetDatabaseDistributor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateState
     *
     * Update a database's state.
     *
     */
    public function testUpdateState()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateUser
     *
     * Update a database's user.
     *
     */
    public function testUpdateUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
